name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build  # Assuming you have a build script in your package.json

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure this runs after the build job

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run tests
        run: npm test  # Assuming you have tests defined in your package.json

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure this runs after the test job
    if: github.ref == 'refs/heads/main'  # Only deploy from the main branch

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Deploy to Production
        run: |
          echo "Deploying to production server..."
          # Add your deployment commands here
          # Example:
          # ssh user@server "cd /path/to/app && git pull && npm install && pm2 restart all"

